
skillMetadata:
  sections:
    - name: General settings
      fields:
        - name: enabled
          type: checkbox
          label: Enable quiet hours
          value: "false"
    - name: Schedule settings
      fields:
        - type: label
          label: Start quiet hours at
        - type: select
          label: Hour
          name: start_time_hour
          value: "22"
          options: 0|00;1|01;2|02;3|03;4|04;5|05;6|06;7|07;8|08;9|09;10|10;11|11;12|12;13|13;14|14;15|15;16|16;17|17;18|18;19|19;20|20;21|21;22|22;23|23
        - name: start_time_min
          type: select
          label: Minute
          options: 00|00;05|05;10|10;15|15;20|20;25|25;30|30;35|35;40|40;45|45;50|50;55|55
          value: "00"
        - type: label
          label: End quiet hours at
        - name: end_time_hour
          type: select
          label: "Hour"
          value: "08"
          options: 00|00;1|01;2|02;3|03;4|04;5|05;6|06;7|07;8|08;9|09;10|10;11|11;12|12;13|13;14|14;15|15;16|16;17|17;18|18;19|19;20|20;21|21;22|22;23|23
        - name: end_time_min
          type: select
          label: "Minute"
          options: 00|00;05|05;10|10;15|15;20|20;25|25;30|30;35|35;40|40;45|45;50|50;55|55
          value: "00"
    - name: Actions settings
      fields:
        - type: label
          label: What to do during quiet hours
        - type: label
          label: Set speakers volume to
        - name: set_volume_to
          type: number
          label: "%" 
          value: 0
